# Generated by Django 3.2 on 2021-12-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('TR', 'Transgender')], max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('license_number', models.CharField(max_length=45)),
                ('license_document', models.FileField(upload_to='media/documents/')),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Driver',
                'get_latest_by': 'created_dtm',
            },
        ),
    ]
