# Generated by Django 3.2 on 2021-12-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20211206_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingordersmodel',
            old_name='invoice_amount',
            new_name='package_value',
        ),
        migrations.RemoveField(
            model_name='shippingordersmodel',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='shippingordersmodel',
            name='vehicle_no',
        ),
        migrations.AddField(
            model_name='shippingordersmodel',
            name='billing_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='shippingordersmodel',
            name='consignee_place',
            field=models.CharField(choices=[('indore', 'Indore'), ('ahmedabad', 'Ahmedabad')], default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='shippingordersmodel',
            name='consignor_place',
            field=models.CharField(default='Coimbatore', max_length=15),
        ),
        migrations.AddField(
            model_name='shippingordersmodel',
            name='door_collection',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippingordersmodel',
            name='door_delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippingordersmodel',
            name='freight_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippingordersmodel',
            name='hamali_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippingordersmodel',
            name='lr_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippingordersmodel',
            name='other_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippingordersmodel',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippingordersmodel',
            name='payment_status',
            field=models.CharField(choices=[('to_pay', 'To Pay'), ('tbb', 'To be Billed'), ('paid', 'PAID')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='shippingordersmodel',
            name='total_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='actual_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='charged_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='consignor',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='gs_tax_payable',
            field=models.CharField(choices=[('Consignee', 'Consignee'), ('Consignor', 'Consignor'), ('IPL', 'IPL')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='invoice_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='invoice_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shippingordersmodel',
            name='package_description',
            field=models.CharField(max_length=115),
        ),
    ]
