# Generated by Django 3.2 on 2021-12-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20211211_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermodel',
            name='address_permanent',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
