# Generated by Django 3.2 on 2021-12-05 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPLUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('created_dtm', models.DateTimeField(default=datetime.datetime(2021, 12, 5, 13, 37, 11, 86579, tzinfo=utc), verbose_name='Created')),
                ('activated', models.BooleanField(default=False, verbose_name='Is Account Activated?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Superuser?')),
            ],
            options={
                'db_table': 'users',
                'get_latest_by': 'created_dtm',
            },
        ),
    ]
