# Generated by Django 3.2 on 2021-12-06 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipluser',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='ipluser',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='ipluser',
            name='created_dtm',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 8, 4, 17, 122218, tzinfo=utc), verbose_name='Created'),
        ),
    ]
