# Generated by Django 3.2 on 2021-12-10 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211206_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipluser',
            name='created_dtm',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 14, 58, 50, 737297, tzinfo=utc), verbose_name='Created'),
        ),
    ]
