# Generated by Django 3.2 on 2021-12-11 03:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_ipluser_created_dtm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipluser',
            name='created_dtm',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 3, 42, 1, 668169, tzinfo=utc), verbose_name='Created'),
        ),
    ]
